language: node_js
node_js:
  - "node"
before_install:
- printf "@fortawesome:registry=https://npm.fontawesome.com/" >> .yarnrc
- printf "\n" >> .yarnrc
- printf "//npm.fontawesome.com/:_authToken=${FA_AUTH_TOKEN}" >> .yarnrc
